In [5]:
import pandas as pd

df = pd.read_csv("sentimentdataset.csv")

In [6]:
df.head()

,Unnamed: 0.1,Unnamed: 0,Text,Sentiment,Timestamp,User,Platform,Hashtags,Retweets,Likes,Country,Year,Month,Day,Hour
0,0,0,Enjoying a beautiful day at the park! ...,Positive,2023-01-15 12:30:00,User123,Twitter,#Nature #Park,15.0,30.0,USA,2023,1,15,12
1,1,1,Traffic was terrible this morning. ...,Negative,2023-01-15 08:45:00,CommuterX,Twitter,#Traffic #Morning,5.0,10.0,Canada,2023,1,15,8
2,2,2,Just finished an amazing workout! ðŸ’ª ...,Positive,2023-01-15 15:45:00,FitnessFan,Instagram,#Fitness #Workout,20.0,40.0,USA,2023,1,15,15
3,3,3,Excited about the upcoming weekend getaway! ...,Positive,2023-01-15 18:20:00,AdventureX,Facebook,#Travel #Adventure,8.0,15.0,UK,2023,1,15,18
4,4,4,Trying out a new recipe for dinner tonight. ...,Neutral,2023-01-15 19:55:00,ChefCook,Instagram,#Cooking #Food,12.0,25.0,Australia,2023,1,15,19

In [7]:
df = df[['Text', 'Sentiment']]

In [13]:
df['Sentiment'] = df['Sentiment'].str.strip().str.lower()

# Display the unique sentiment labels again after cleaning
print(df['Sentiment'].unique())

['positive' 'negative' 'neutral' 'anger' 'fear' 'sadness' 'disgust'
 'happiness' 'joy' 'love' 'amusement' 'enjoyment' 'admiration' 'affection'
 'awe' 'disappointed' 'surprise' 'acceptance' 'adoration' 'anticipation'
 'bitter' 'calmness' 'confusion' 'excitement' 'kind' 'pride' 'shame'
 'elation' 'euphoria' 'contentment' 'serenity' 'gratitude' 'hope'
 'empowerment' 'compassion' 'tenderness' 'arousal' 'enthusiasm'
 'fulfillment' 'reverence' 'despair' 'grief' 'loneliness' 'jealousy'
 'resentment' 'frustration' 'boredom' 'anxiety' 'intimidation'
 'helplessness' 'envy' 'regret' 'curiosity' 'indifference' 'numbness'
 'melancholy' 'nostalgia' 'ambivalence' 'determination' 'zest' 'hopeful'
 'proud' 'grateful' 'empathetic' 'compassionate' 'playful' 'free-spirited'
 'inspired' 'confident' 'bitterness' 'yearning' 'fearful' 'apprehensive'
 'overwhelmed' 'jealous' 'devastated' 'frustrated' 'envious' 'dismissive'
 'thrill' 'bittersweet' 'overjoyed' 'inspiration' 'motivation'
 'contemplation' 'joyfulreunion' 'satisfaction' 'blessed' 'reflection'
 'appreciation' 'confidence' 'accomplishment' 'wonderment' 'optimism'
 'enchantment' 'intrigue' 'playfuljoy' 'mindfulness' 'dreamchaser'
 'elegance' 'whimsy' 'pensive' 'harmony' 'creativity' 'radiance' 'wonder'
 'rejuvenation' 'coziness' 'adventure' 'melodic' 'festivejoy'
 'innerjourney' 'freedom' 'dazzle' 'adrenaline' 'artisticburst'
 'culinaryodyssey' 'resilience' 'immersion' 'spark' 'marvel' 'heartbreak'
 'betrayal' 'suffering' 'emotionalstorm' 'isolation' 'disappointment'
 'lostlove' 'exhaustion' 'sorrow' 'darkness' 'desperation' 'ruins'
 'desolation' 'loss' 'heartache' 'solitude' 'positivity' 'kindness'
 'friendship' 'success' 'exploration' 'amazement' 'romance' 'captivation'
 'tranquility' 'grandeur' 'emotion' 'energy' 'celebration' 'charm'
 'ecstasy' 'colorful' 'hypnotic' 'connection' 'iconic' 'journey'
 'engagement' 'touched' 'suspense' 'triumph' 'heartwarming' 'obstacle'
 'sympathy' 'pressure' 'renewed effort' 'miscalculation' 'challenge'
 'solace' 'breakthrough' 'joy in baking' 'envisioning history'
 'imagination' 'vibrancy' 'mesmerizing' 'culinary adventure'
 'winter magic' 'thrilling journey' "nature's beauty" 'celestial wonder'
 'creative inspiration' 'runway creativity' "ocean's freedom"
 'whispers of the past' 'relief' 'embarrassed' 'mischievous' 'sad' 'hate'
 'bad' 'happy']

In [14]:
filtered_df = df[df['Sentiment'].isin(['positive','negative','neutral'])]

In [16]:
filtered_df

                                                  Text Sentiment
0     Enjoying a beautiful day at the park!        ...  positive
1     Traffic was terrible this morning.           ...  negative
2     Just finished an amazing workout! ðŸ’ª          ...  positive
3     Excited about the upcoming weekend getaway!  ...  positive
4     Trying out a new recipe for dinner tonight.  ...   neutral
..                                                 ...       ...
713  Participating in a science fair to showcase a ...   neutral
714  Attending a workshop on time management to enh...   neutral
715  Volunteering at a local charity event to give ...   neutral
716  Collaborating on a group project to promote te...   neutral
717  Participating in a debate club to enhance crit...   neutral

[67 rows x 2 columns]

In [17]:
sentiment_counts = filtered_df['Sentiment'].value_counts()

print(sentiment_counts)

Sentiment
positive    45
neutral     18
negative     4
Name: count, dtype: int64

In [18]:
filtered_df.to_csv('test_dataset.csv')